@host=http://localhost:5080

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Amichai",
    "lastName": "Mantinband",
    "email": "amichai@mantinband.com",
    "password": "Amiko1232!"
}

###
